### ISSUE TITLE
Allow for custom comparison of arguments

### ISSUE THREAD

**Issue by linkrope** [QAston/DMocks-revived#4]
When a function to be mocked has an argument for which the comparison with `==` does not work, you have to switch to `ignoreArgs` and to `action`. In the action block you have to explicitly compare all simple arguments with `==` and the offending one with your own custom comparison.

One example of an offending argument is `Nullable!T()`, where `==` throws.

It would be nice, when the comparison of arguments could be customized. Then you would provide a specialized equality predicate for a type like `Nullable!JSONValue` (or even `JSONValue`) and could use the mock framework as usual.

**Comment by boloboloda** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
masterdxy, @syfari, @intvirtue, @qa1, @thangdev, @husua01, @feronera, @d33pfri3d, @Vialiceq, @Himangshu1086, @ChaseWohrle, @That1bull-BK, @gorkemkeles, @thaerlabs, @sianliu, @magohome, @derick003, @CryptoskinR, @zhaochunqi, @khaled

**Comment by jacky-xbb** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
dogukanakkaya, @Setland34, @Guillerbr, @Easoncc, @lishuailibertine, @io12, @hongyanh, @ethgallucci, @gistrec, @lorry3, @EurekaUA, @tinybike, @titangene, @arcayne, @DoroshinAnton, @SunSchizzzz, @vikasr111, @monoman, @fiubit, @nillptr

**Comment by QAston** [comment]
For some reason spam bots like this issue, so I'm closing it.
